### ISSUE TITLE
请问下为什么新版本废弃了 constate 那一套架构，换成了 rematch 这一套方案

### ISSUE THREAD

**Issue by chnliquan** [ice-lab/icestore#101]
想请教下，之前的方案有什么问题吗，以及 0.x 的时候使用的 useState 内部做调度，后来也废弃了，望详细解答下

**Comment by alvinhui** [comment]
原因在 https://github.com/ice-lab/icestore/pull/82 上有描述。不知道这里面的描述是否可以解答你的疑问？
