### ISSUE TITLE
Bug: Uncaught TypeError: Cannot assign to read only property 'loading' of object '#<Object>'

### ISSUE THREAD

**Issue by chenbin92** [ice-lab/icestore#107]
@ice/store version:  1.3.5

## Steps To Reproduce

1.  代码示例：https://github.com/ice-lab/icejs/blob/master/examples/basic-store
2. 重现步骤：点击切换页面，但不是固定重现

![demo](https://user-images.githubusercontent.com/3995814/80075687-ab537100-857d-11ea-9fb3-6295522e23f8.gif)

Link to code example:

## The current behavior

![image](https://user-images.githubusercontent.com/3995814/80075824-db027900-857d-11ea-85e1-e9738b437b23.png)

## The expected behavior

修复错误

**Comment by alvinhui** [comment]
https://github.com/ice-lab/icestore/issues/94
