### ISSUE TITLE
dispatch typings

### ISSUE THREAD

**Issue by avalanche1** [ice-lab/icestore#112]
How can I type annotate `dispatch` here?:
![image](https://user-images.githubusercontent.com/10534563/81498167-013d4e00-92cc-11ea-9090-ed44a369430e.png)
`icestore` doesnt export `RootDispatch` type.

**Comment by imsobear** [comment]
[src/store.ts](https://codesandbox.io/s/admiring-mendel-zllqe?file=/src/store.ts:1-344) export `RootDispatch`:

```typescript
// src/store.ts
import { createStore, IcestoreRootState, IcestoreDispatch } from '@ice/store';
import models from './models';

const store = createStore(models);

export default store;
export type Models = typeof models;
export type Store = typeof store;
export type RootDispatch = IcestoreDispatch<Models>;
export type RootState = IcestoreRootState<Models>;
```

```js
// models/todo.ts
import { RootDispatch } from '../store';
```

And we will update the docs.

**Comment by avalanche1** [comment]
Thx for the example. Unfortunately `RootDispatch` doesnt offer any type completion. Can this be add plz?

**Comment by avalanche1** [comment]
![image](https://user-images.githubusercontent.com/10534563/81593176-bb65b000-93c7-11ea-86c5-a6315b623d86.png)
![image](https://user-images.githubusercontent.com/10534563/81593195-c28cbe00-93c7-11ea-931f-b209506218f6.png)
![image](https://user-images.githubusercontent.com/10534563/81593222-cd475300-93c7-11ea-8a59-5bd176c6e167.png)

**Comment by avalanche1** [comment]
Also, TS cannot infer types from `this` in effects functions:
![image](https://user-images.githubusercontent.com/10534563/81594320-62971700-93c9-11ea-9f99-4f4b9a539e57.png)

**Comment by imsobear** [comment]
@alvinhui

**Comment by ishenli** [comment]
遇到类似的问题

![image](https://user-images.githubusercontent.com/2113885/82747276-eab5ed00-9dc9-11ea-8e60-e2738c093e4c.png)

代码：https://codesandbox.io/s/determined-franklin-lunsf?file=/src/model/bar.ts:444-486

貌似把`IcestoreDispatch`改成不会报错

```ts
export declare type IcestoreDispatch<M extends Models> = (M extends Models ? ExtractIcestoreDispatchersFromModels<M> : {
    [key: string]: {
        [key: string]: IcestoreDispatcher | IcestoreDispatcherAsync;
    };
}) & (IcestoreDispatcher | IcestoreDispatcherAsync) & (Redux.Dispatch<any>);


```

**Comment by alvinhui** [comment]
see: https://codesandbox.io/s/github/ice-lab/icestore/tree/master/examples/todos?module=/src/index.tsx&file=/src/models/index.ts

you must add interface to avoid recursive type checking.
