### ISSUE TITLE
Feature: support custom selector

### ISSUE THREAD

**Issue by Zaynex** [ice-lab/icestore#118]
目前 useModel 只支持传入单个字符获取一个 model 的 state。
希望能够渗入获得具体 model 的 state 的特定值。

比如：
```
const nestedCounter = {
  state: {
    counter: 0,
    otherCount: 0
  },
  reducers: {
    incrementNested: prevState => {
      prevState.counter += 1;
    },
    incrementOther: prevState => {
      prevState.otherCount += 1;
    }
  }
};
```

如果组件A 只是调用 incrementNested 方法，而组件B只是依赖了 otherCount 的数据。组件B 依然会触发 re-render。（当然可以通过 return 的时候 useMemo() 来解决这个问题）

如果 useModel 的 selector 可以暴露给用户，或者我们提供自定义的对象取值，会不会更香？

比如：
```
const [ counter]  = useModel('nestedCounter.counter')
```

```
const [otherCount] = useModel('nestedCounter.othterCount');
```

或者
```
const [counter] = useModel(state => state.nestedCounter.counter)
```

https://codesandbox.io/s/brave-fire-jnjoy?file=/src/index.tsx

**Comment by fantasticsoul** [comment]
你看下这个示例能满足你的需求吗（参考你的例子修改了下）
https://codesandbox.io/s/bitter-tdd-pch5n?file=/src/index.tsx
其实你的核心诉求是需要有一个运行时的依赖收集机制
https://codesandbox.io/s/dep-collection-uiqzn?file=/src/App.js

**Comment by Zaynex** [comment]
@fantasticsoul  对 ts支持如何？ 这个库对 ts 支持有些缺陷。

**Comment by fantasticsoul** [comment]
> @fantasticsoul 对 ts支持如何？ 这个库对 ts 支持有些缺陷。

额，我敢说concent对ts支持是最友好的库了😀，因为一切皆函数，不需要任何hack，提供了最详细的类型支持文档，实例里dispatch字符串是因为model声明为一个对象，如果是写在文件里在导出给run装配，其实可以基于引用调用

```js
// code in models/foo/reducer.js
export function methodA(payload){
  return {fieldA: payload}
}

export function methodB(payload){
  return {fieldB: payload}
}

// 组合多个reducer
export async function methodCombine(p, m ,ac){
  await ac.dispatch(methodA, 1);//此处基于函数引用直接调用
  await ac.dispatch(methodB, 2);
}
```

更详细ts实例参考这里：
https://codesandbox.io/s/concent-guide-ts-zrxd5

更多信息见git
https://github.com/concentjs/concent
或官网
https://concentjs.github.io/concent-doc/

相比其他状态管理方案，concent的巨大优势
1 无需顶层Provider
2 分离是配置model
3 运行时依赖收集，保持最小粒度更新
4 非常完整与强大的ts支持
5 ssr同样无缝支持 https://github.com/concentjs/ssr-demo-1

所有的一切都是为了让用户写得更爽，运行得更高效哦。
希望你细细体会下你的这个例子，打开console看下日志，给你加了toggle开关
https://codesandbox.io/s/bitter-tdd-pch5n?file=/src/index.tsx

**Comment by alvinhui** [comment]
@Zaynex 对于你的原始需求，可以用 useSelector 来达到，当前这不是一个开放的 API。

示例：https://codesandbox.io/s/busy-kepler-2lobg?file=/src/index.tsx

另外你说的 TS 支持缺陷是指？
