### ISSUE TITLE
Bug: 文档错误

### ISSUE THREAD

**Issue by kotot** [ice-lab/icestore#130]
文档 https://github.com/ice-lab/icestore/blob/master/docs/api.zh-CN.md
const todos = {
  state: [
    {
      title: 'Learn typescript',
      done: true,
    },
  ],
  reducers: {
    // 正确用法
    add(state, todo) {
      state.push(todo);
    },
    // 错误用法
    add(state, title, done) {
      state.push({ title, done });
    },
  },
};

// 使用时：
function Component() {
  const { add } = store.useModelDispathers('todos');
  function handleClick () {
    add({ title: 'Learn React', done: false }); // 正确用法
    add('Learn React', false); // 错误用法
  }
}

这里的state 才进行了代码，而对payload 解构是没有影响的

**Comment by alvinhui** [comment]
抱歉我没能理解「错误」是指？可以使用 diff 格式来说明一下？
