### ISSUE TITLE
react version error

### ISSUE THREAD

**Issue by phobal** [ice-lab/icestore#28]
Issue is uniformly managed in [alibaba/ice](https://github.com/alibaba/ice/issues). The issues not in alibaba/ice will be closed directly.

Issue 统一在 [alibaba/ice](https://github.com/alibaba/ice/issues) 仓库管理，不在 alibaba/ice 的 issue 会被直接关闭。

![image](https://user-images.githubusercontent.com/9244211/63068310-3f782d80-bf45-11e9-8bee-b0a10414310f.png)

这里的 peerDependencies 中依赖的 react 版本应该是 `^16.8.0` 吧？

**Comment by imsobear** [comment]
是的 @phobal 可以提个 PR 哈

**Comment by phobal** [comment]
已修改  https://github.com/ice-lab/icestore/pull/29
