### ISSUE TITLE
createAction的函数是否应该有返回值？

### ISSUE THREAD

**Issue by 1120340041** [ice-lab/icestore#32]
stroe.ts里面81号的await result这部分是不是应该改成

   const resultData = await result
   afterExec()
   return resultData

**Comment by temper357** [comment]
正在开发的新版本已支持返回 action 的返回值，待发布后通知你

**Comment by temper357** [comment]
@1120340041 icestore 0.3.0 已发布，支持返回 action 返回值，可参考线上示例 https://codesandbox.io/s/icestore-hs9fe
