### ISSUE TITLE
子组件会多 render 一次的问题

### ISSUE THREAD

**Issue by ti-tian** [ice-lab/icestore#35]
在线示例：https://codesandbox.io/s/green-star-f19k0

如果把源码中 `private setState()` 中的遍历触发 forceupdate 放在  `unstable_batchedUpdates` 中执行，可以避免同步 action 触发时候 ，子组件重新 render 。

但是 ，action 还可以返回一个 promise ，这样的话如果需要 action 的 loading 状态，就会连续两次触发 forceupdate ，总是会触发子组件 render 两次的。

**Comment by temper357** [comment]
你的诉求是同步的 action 执行时，不额外执行 loading 状态的一次 forceUpdate 吗？

**Comment by ti-tian** [comment]
不是，我指的是子组件重新渲染其实是不应该的，如果全都用同步 action 可以借助批处理解决掉，但是如果是异步 action 就很难做了。

**Comment by temper357** [comment]
异步 action 与同步 action 的区别是异步 action 执行时会多渲染一次，以拿到异步 action 的执行状态，可以设置 disableLoading 将这个功能禁掉 https://github.com/ice-lab/icestore/blob/master/README.zh-CN.md#%E5%BC%82%E6%AD%A5-action-%E6%89%A7%E8%A1%8C%E7%8A%B6%E6%80%81

**Comment by ti-tian** [comment]
我的例子中其实想做的是同时改变子组件和父组件的 state ，但是无论是不是同步 action ，都会导致子组件多一次 render，这个不是很合理。

**Comment by temper357** [comment]
明白你意思了，多 render 一次应该从 icestore 架构上解决，我抽时间解决下

**Comment by ti-tian** [comment]
好的 谢谢

**Comment by namepain** [comment]
暂时好像可以使用 React.memo 防止子组件重复渲染。期待官方给出架构上的解决方案

**Comment by Lizhooh** [comment]
问题解决了吗？

**Comment by alvinhui** [comment]
其实应该是不推荐在父组件使用了 useStore 后还在子组件使用相同的 useStore
