### ISSUE TITLE
icestore有考虑支持react class api吗？毕竟目前的项目里面大部分还是基于class组件

### ISSUE THREAD

**Issue by Fuphoenixes** [ice-lab/icestore#40]
Issue is uniformly managed in [alibaba/ice](https://github.com/alibaba/ice/issues). The issues not in alibaba/ice will be closed directly.

Issue 统一在 [alibaba/ice](https://github.com/alibaba/ice/issues) 仓库管理，不在 alibaba/ice 的 issue 会被直接关闭。

**Comment by imsobear** [comment]
相同 issue: https://github.com/alibaba/ice/issues/2953
进行中的 MR: https://github.com/ice-lab/icestore/pull/39
