### ISSUE TITLE
在new Icestore() 出现错误，

### ISSUE THREAD

**Issue by xyy7260** [ice-lab/icestore#62]
版本
 "@ice/store": "^1.0.0",
  "@ice/store-logger": "^0.1.0",
 "react": "^16.9.0",
——————
当按照你们的demo去创建store的时候出现在这一步
const icestore = new Icestore();

TypeError: _ice_store__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor
Module../src/stores/index.js
src/stores/index.js:5
  2 | import logger from '@ice/store-logger';
  3 | import home from './home/home';
  4 | 
> 5 | const icestore = new Icestore();
  6 | const middlewares = [];
  7 | if (process.env.NODE_ENV !== 'production') {
  8 | 	middlewares.push(logger);

**Comment by xyy7260** [comment]
是不是版本的问题造成的， 我在我项目包里面并没有发现registerStore 只有
4个
export * from './createContainer';
export * from './createStore';
export * from './createModel';
export * from './types';

**Comment by alvinhui** [comment]
1.0 的 API 变更了，具体看 README

**Comment by xyy7260** [comment]
@alvinhui  好的，   官网上的展示也没更新吧

**Comment by alvinhui** [comment]
@xyy7260 是的，官网上的文档暂时还没有更新，以这个仓库的 README 和 example 为准

**Comment by xyy7260** [comment]
@alvinhui   好的谢谢
