### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/icestore#68]
- feature: 不可变数据的支持，简化模型定义；
- feature: 支持只使用不订阅：https://codesandbox.io/s/gallant-fast-w8klw 第三十八行代码获取到最新的 state；
- test: 补充单元测试；

**Comment by alvinhui** [comment]
邀请一下 @luhc228 有兴趣可以看看单元测试怎么写。

**Comment by luhc228** [comment]
> 邀请一下 @luhc228 有兴趣可以看看单元测试怎么写。

OK, 这几天可以搞一下，我自己新建一个分支做下unit test？

**Comment by alvinhui** [comment]
> > 邀请一下 @luhc228 有兴趣可以看看单元测试怎么写。
> 
> OK, 这几天可以搞一下，我自己新建一个分支做下unit test？

嗯，可以 PR 到这个分支。
