### ISSUE TITLE
Bug: 类型推导问题

### ISSUE THREAD

**Issue by imsobear** [ice-lab/icestore#71]
@ice/store version: 1.1.0

## Steps To Reproduce

```typescript
interface IState {
  count: number;
};

const counter = {
  state: {
    count: 20,
  },
  reducers: {
    addCount(prevState: IState, count: number): IState {
      return {
        ...prevState,
        count: prevState.count += count,
      };
    },
  },
  effects: {
    async addCountAsync(prevState: IState, count: number, actions): Promise<void> {
      await new Promise((resolve) => setTimeout(resolve, 0.5 * 1000));
      actions.addCount(count);
    }
  }
}

export default counter;
```

Link to code example:

https://github.com/imsobear/icejs-store-demo

## The current behavior

useModel:

![image](https://user-images.githubusercontent.com/2505411/76384550-398ee180-639a-11ea-8075-bb6d2e1958c8.png)

useModelActions:

![image](https://user-images.githubusercontent.com/2505411/76384529-25e37b00-639a-11ea-82a7-298d36b65b51.png)

useModelEffectsState:

![image](https://user-images.githubusercontent.com/2505411/76384565-44497680-639a-11ea-8c56-02406cf3d6ed.png)

## The expected behavior

You know.

**Comment by alvinhui** [comment]
https://github.com/ice-lab/icestore/pull/72
