### ISSUE TITLE
Bug: State被Freeze后无法进行更新

### ISSUE THREAD

**Issue by luhc228** [ice-lab/icestore#94]
## Question Desc
在 codesandbox(link: https://codesandbox.io/s/determined-kepler-khu47?file=/src/models/todos.ts) 中修改 store 中的代码后，会出现下面的报错
![image](https://user-images.githubusercontent.com/44047106/78806413-3157af80-79f5-11ea-80fa-b2c207031bfa.png)

@ice/store version: 1.3.3

Link to code example:
codesanbox link: https://codesandbox.io/s/determined-kepler-khu47?file=/src/models/todos.ts

## The expected behavior
修改代码后不报错

**Comment by alvinhui** [comment]
看起来是 Hot Reload 下的问题。
